# Generated by Django 3.2 on 2021-04-14 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jmeno', models.CharField(max_length=30, verbose_name='Jméno')),
                ('prijmeni', models.CharField(max_length=30, null=True, verbose_name='Přijmení')),
                ('narozeni', models.DateTimeField(verbose_name='Narození')),
                ('zivotopis', models.TextField(verbose_name='Životopis autora')),
            ],
            options={
                'ordering': ['jmeno', '-narozeni'],
            },
        ),
        migrations.CreateModel(
            name='Ctenar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jmeno', models.CharField(max_length=30, verbose_name='Jméno')),
                ('prijmeni', models.CharField(max_length=30, null=True, verbose_name='Přijmení')),
                ('narozeni', models.DateTimeField(verbose_name='Narození')),
            ],
            options={
                'ordering': ['jmeno', '-narozeni'],
            },
        ),
        migrations.CreateModel(
            name='Kniha',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=30, verbose_name='ISBN knihy')),
                ('titul', models.CharField(max_length=100, verbose_name='Název díla')),
                ('zanr', models.CharField(max_length=30, verbose_name='Žánr')),
                ('vydani', models.DateTimeField(verbose_name='Datum vydání knihy')),
                ('obsah', models.TextField(verbose_name='Obsah knihy')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knihovna_app.autor')),
                ('ctenar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knihovna_app.ctenar')),
            ],
            options={
                'ordering': ['-vydani', 'titul'],
            },
        ),
    ]
