# Generated by Django 3.1.7 on 2021-05-21 16:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import knihovna_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=30, verbose_name='Jméno')),
                ('prijmeni', models.CharField(max_length=30, null=True, verbose_name='Přijmení')),
                ('narozeni', models.DateTimeField(verbose_name='Narození')),
                ('zivotopis', models.TextField(default='', verbose_name='Životopis autora')),
            ],
            options={
                'ordering': ['jmeno', '-narozeni'],
            },
        ),
        migrations.CreateModel(
            name='Zanr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(help_text='Zadej název žánru', max_length=25, unique=True, verbose_name='Název žánru')),
            ],
            options={
                'verbose_name': 'Žánr',
                'verbose_name_plural': 'Žánry',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Kniha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=30, verbose_name='ISBN knihy')),
                ('titul', models.CharField(max_length=100, verbose_name='Název díla')),
                ('runtime', models.IntegerField(blank=True, help_text='Please enter an integer value (minutes)', null=True, verbose_name='Runtime')),
                ('hodnoceni', models.FloatField(default=5, help_text='Od 1 do 10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Hodnoceni')),
                ('vydani', models.DateField(blank=True, help_text='Zadejte datum vydání', null=True, verbose_name='Datum Vydání')),
                ('obsah', models.TextField(default='', verbose_name='Obsah knihy')),
                ('obal', models.ImageField(blank=True, null=True, upload_to='kniha/obal/%Y/%m/%d/', verbose_name='Obal')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knihovna_app.autor')),
                ('zanry', models.ManyToManyField(help_text='Vyber žánry knihy', to='knihovna_app.Zanr')),
            ],
            options={
                'ordering': ['-vydani', 'titul'],
            },
        ),
        migrations.CreateModel(
            name='Priloha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titul', models.CharField(default='', max_length=200, verbose_name='Titul')),
                ('uprava', models.DateTimeField(auto_now=True)),
                ('soubor', models.FileField(null=True, upload_to=knihovna_app.models.attachment_path, verbose_name='Soubor')),
                ('typ', models.CharField(choices=[('Audio', 'Audio'), ('Video', 'Video'), ('Text', 'Text'), ('Jiné', 'Jiné')], default='Audio', help_text='Vyber povolenou přílohu', max_length=5, verbose_name='Typ přílohy')),
                ('kniha', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='knihovna_app.kniha')),
            ],
            options={
                'order_with_respect_to': 'kniha',
            },
        ),
    ]
