# Generated by Django 3.2 on 2021-04-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=30, verbose_name='Jméno')),
                ('prijmeni', models.CharField(max_length=30, null=True, verbose_name='Přijmení')),
                ('narozeni', models.DateTimeField(verbose_name='Narození')),
                ('zivotopis', models.TextField(verbose_name='Životopis autora')),
            ],
            options={
                'ordering': ['jmeno', '-narozeni'],
            },
        ),
        migrations.CreateModel(
            name='ctenar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=30, verbose_name='Jméno')),
                ('prijmeni', models.CharField(max_length=30, null=True, verbose_name='Přijmení')),
                ('narozeni', models.DateTimeField(verbose_name='Narození')),
            ],
            options={
                'ordering': ['jmeno', '-narozeni'],
            },
        ),
        migrations.CreateModel(
            name='kniha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=30, verbose_name='ISBN knihy')),
                ('titul', models.CharField(max_length=100, verbose_name='Název díla')),
                ('zanr', models.CharField(max_length=30, verbose_name='Žánr')),
                ('vydani', models.DateTimeField(verbose_name='Datum vydání knihy')),
                ('obsah', models.TextField(verbose_name='Obsah knihy')),
            ],
            options={
                'ordering': ['-vydani', 'titul'],
            },
        ),
    ]
