# Generated by Django 3.1.7 on 2021-06-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='', max_length=40, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=30, verbose_name='ISBN'),
        ),
    ]
