# Generated by Django 3.1.7 on 2021-06-19 20:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knihovna_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='', max_length=40, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='autor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=30, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.DateField(blank=True, help_text='Enter a valid date', null=True, verbose_name='Release date'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('rate', models.IntegerField(default=5, help_text='Please enter an integer value (range 1 - 10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Rate')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knihovna_app.book')),
            ],
            options={
                'order_with_respect_to': 'book',
            },
        ),
    ]
