# Generated by Django 3.2 on 2021-04-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='zivotopis',
            field=models.TextField(default='', verbose_name='Životopis autora'),
        ),
        migrations.AlterField(
            model_name='kniha',
            name='obsah',
            field=models.TextField(default='', verbose_name='Obsah knihy'),
        ),
    ]
