# Generated by Django 3.2 on 2021-05-12 19:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import knihovna_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna_app', '0002_auto_20210414_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(null=True, upload_to=knihovna_app.models.attachment_path, verbose_name='File')),
                ('type', models.CharField(choices=[('Poster', 'Poster'), ('Opening', 'Opening'), ('text', 'Text'), ('video', 'Video'), ('other', 'Other'), ('Manga', 'Manga')], default='Poster', help_text='Select allowed attachment type', max_length=7, verbose_name='Attachment type')),
            ],
        ),
        migrations.AlterField(
            model_name='kniha',
            name='vydani',
            field=models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1800), knihovna_app.models.maximalni_rok], verbose_name='Vydání'),
        ),
        migrations.AddField(
            model_name='kniha',
            name='attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='knihovna_app.attachment'),
        ),
    ]
