# Generated by Django 3.1.7 on 2021-05-21 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna_app', '0002_auto_20210521_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kniha',
            name='runtime',
        ),
        migrations.AddField(
            model_name='kniha',
            name='strany',
            field=models.IntegerField(blank=True, help_text='Zadejte počet stránek díla', null=True, verbose_name='Počet stránek'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='narozeni',
            field=models.DateField(blank=True, help_text='Zadejte datum narození', null=True, verbose_name='Datum narození'),
        ),
        migrations.AlterField(
            model_name='kniha',
            name='hodnoceni',
            field=models.FloatField(default=5, help_text='Od 1 do 10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Hodnocení'),
        ),
        migrations.AlterField(
            model_name='kniha',
            name='vydani',
            field=models.DateField(blank=True, help_text='Zadejte datum vydání', null=True, verbose_name='Datum vydání'),
        ),
    ]
