# Generated by Django 3.1.7 on 2021-05-21 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna_app', '0003_auto_20210521_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kniha',
            old_name='zanry',
            new_name='zanr',
        ),
    ]
