# Generated by Django 3.2 on 2021-05-12 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna_app', '0004_auto_20210512_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='kniha',
            name='hodnoceni',
            field=models.FloatField(default=5, help_text='Od 1 do 10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Hodnoceni'),
        ),
    ]
