# Generated by Django 3.1.7 on 2021-05-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna_app', '0004_auto_20210521_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priloha',
            name='typ',
            field=models.CharField(choices=[('Audio', 'Audio'), ('Video', 'Video'), ('Text', 'Text'), ('Jiné', 'Jiné')], default='Image', help_text='Vyber povolenou přílohu', max_length=5, verbose_name='Typ přílohy'),
        ),
    ]
