# Generated by Django 3.2 on 2021-05-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna_app', '0005_kniha_hodnoceni'),
    ]

    operations = [
        migrations.AddField(
            model_name='kniha',
            name='obal',
            field=models.ImageField(blank=True, null=True, upload_to='kniha/obal/%Y/%m/%d/', verbose_name='Obal'),
        ),
    ]
