# Generated by Django 3.1.7 on 2021-05-21 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna_app', '0005_auto_20210521_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zanr',
            options={'ordering': ['nazev']},
        ),
    ]
