# Generated by Django 3.1.7 on 2021-05-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna_app', '0006_auto_20210521_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kniha',
            old_name='zanr',
            new_name='zanry',
        ),
        migrations.AlterField(
            model_name='priloha',
            name='typ',
            field=models.CharField(choices=[('Audio', 'Audio'), ('Video', 'Video'), ('Text', 'Text'), ('Jiné', 'Jiné')], default='image', help_text='Vyber povolenou přílohu', max_length=5, verbose_name='Typ přílohy'),
        ),
    ]
